### ISSUE TITLE
Scripts should have mode 0755

### ISSUE THREAD

**Issue by mlangbehn** [odrodrig/meanDevOps#1]
Scripts in the scripts directory have mode 0644, but should be 0755 to allow for execution in CI/CD pipeline...and anywhere else one may wish to run scripts.

**Comment by mlangbehn** [comment]
Resolved.

**Comment by odrodrig** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b483d91f-e9d9-4c0d-95f0-0896fcb83d80?env_id=ibm%3Ayp%3Aus-south "odr-mean-demo"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/38efe4b5-0a8e-4cb7-b16f-020ab5682386 "odr-mean-demo") deployed [meanDevOps](https://github.com/odrodrig/meanDevOps/releases/tag/deploy-ibm-yp-us-south-odrodrig-us.ibm.com-dev-20200121-213547 "deploy-ibm-yp-us-south-odrodrig-us.ibm.com-dev-20200121-213547") to [dev](https://console.bluemix.net/apps/618ff94c-d0a4-47c4-ac97-fabd75ccb676?env_id=ibm:yp:us-south "ibm:yp:us-south:odrodrig@us.ibm.com:dev"), including commit cef9c79af8af4adb4778496dd5b3804146923af6
