### ISSUE TITLE
Remove log tailing in `scripts/deploy.sh`

### ISSUE THREAD

**Issue by mlangbehn** [odrodrig/meanDevOps#3]
This step is redundant, since IBM Cloud DevOps Pipelines shows relevant logs. Also, this step causes the deploy to count as successful, even if the deploy fails.

**Comment by mlangbehn** [comment]
Resolved.

**Comment by odrodrig** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b483d91f-e9d9-4c0d-95f0-0896fcb83d80?env_id=ibm%3Ayp%3Aus-south "odr-mean-demo"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/38efe4b5-0a8e-4cb7-b16f-020ab5682386 "odr-mean-demo") deployed [meanDevOps](https://github.com/odrodrig/meanDevOps/releases/tag/deploy-ibm-yp-us-south-odrodrig-us.ibm.com-dev-20200121-223332 "deploy-ibm-yp-us-south-odrodrig-us.ibm.com-dev-20200121-223332") to [dev](https://console.bluemix.net/apps/618ff94c-d0a4-47c4-ac97-fabd75ccb676?env_id=ibm:yp:us-south "ibm:yp:us-south:odrodrig@us.ibm.com:dev"), including commit 76e0e02ffd97745ed892c689f43643bdd299b98a
